@echo off
echo ####      #### ##########    ############
echo vir##     #### ####    ### ##############
echo  ###t    ####  ####    ### ####
echo   ####  #ual   #########   #### 0nfig
echo    ########    ####    ### ####
echo     ######     ######ox### ##############
echo      ####      ##########    ############
echo VirtualBoxC0nfig
echo [i] Creating vb.vbconf File...
echo ## VirtualBoxC0nfig Configuration File >> vb.vbconf
echo ## Put your code here! You can remove thesese lines as any line starting with ## are ignored. >> vb.vbconf
color a0
echo [!] Succefully created file!
pause
exit